In [4]:
import numpy as np
import pandas as pd
list=[[1,'Smith',50000],[2,'Jones',60000]]
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
df=pd.DataFrame(list)
df

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

In [7]:
df.columns=['Empd','Name','Salary']
df

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      str
 2   Salary  2 non-null      int64
dtypes: int64(2), str(1)
memory usage: 190.0 bytes

In [9]:
df=pd.read_csv(r"C:\Users\keshi\Downloads\50_Startups.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     str
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.5 KB

In [10]:
df.head()
df.tail()

    R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [11]:
df=pd.read_csv(r"C:\Users\keshi\Downloads\employee.csv")

print(df.head())
print(df.tail())
df.info()

   emp id                 name   salary
0       1     SREE VARSSINI K S    5000
1       2           SREEMATHI B    6000
2       3               SREYA G    7000
3       4  SREYASKARI MULLAPUDI    5000
4       5         SRI AKASH U G    8000
   emp id                  name   salary
2       3                SREYA G    7000
3       4   SREYASKARI MULLAPUDI    5000
4       5          SRI AKASH U G    8000
5       6  SRI HARSHAVARDHANAN R    3000
6       7  SRI HARSHAVARDHANAN R    6000
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp id  7 non-null      int64
 1   name    7 non-null      str
 2   salary  7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 410.0 bytes

In [12]:
print(df.salary)
print(type(df.salary))
print(df.salary.mean())
print(df.salary.median())
print(df.salary.mode())
print(df.salary.var())
print(df.salary.std())

0    5000
1    6000
2    7000
3    5000
4    8000
5    3000
6    6000
Name: salary, dtype: int64
<class 'pandas.Series'>
5714.285714285715
6000.0
0    5000
1    6000
Name: salary, dtype: int64
2571428.5714285714
1603.5674514745463

In [13]:
print(df.describe())
print(df.describe(include='all'))

empCol=df.columns
print(empCol)

         emp id       salary
count  7.000000     7.000000
mean   4.000000  5714.285714
std    2.160247  1603.567451
min    1.000000  3000.000000
25%    2.500000  5000.000000
50%    4.000000  6000.000000
75%    5.500000  6500.000000
max    7.000000  8000.000000
          emp id                  name        salary
count   7.000000                      7     7.000000
unique       NaN                      6          NaN
top          NaN  SRI HARSHAVARDHANAN R          NaN
freq         NaN                      2          NaN
mean    4.000000                    NaN  5714.285714
std     2.160247                    NaN  1603.567451
min     1.000000                    NaN  3000.000000
25%     2.500000                    NaN  5000.000000
50%     4.000000                    NaN  6000.000000
75%     5.500000                    NaN  6500.000000
max     7.000000                    NaN  8000.000000
Index(['emp id', 'name ', 'salary'], dtype='str')

In [14]:
emparray=df.values
print(emparray)

employee_DF=pd.DataFrame(emparray,columns=empCol)
employee_DF

[[1 'SREE VARSSINI K S' 5000]
 [2 'SREEMATHI B' 6000]
 [3 'SREYA G' 7000]
 [4 'SREYASKARI MULLAPUDI' 5000]
 [5 'SRI AKASH U G' 8000]
 [6 'SRI HARSHAVARDHANAN R' 3000]
 [7 'SRI HARSHAVARDHANAN R' 6000]]

  emp id                  name  salary
0      1      SREE VARSSINI K S   5000
1      2            SREEMATHI B   6000
2      3                SREYA G   7000
3      4   SREYASKARI MULLAPUDI   5000
4      5          SRI AKASH U G   8000
5      6  SRI HARSHAVARDHANAN R   3000
6      7  SRI HARSHAVARDHANAN R   6000